### ISSUE TITLE
Privacy Policy needs to be accepted to comply with GDPR

### ISSUE THREAD

**Issue by netzhuffle** [iqasport/referee_hub#50]
GDPR forces us to have referees (at least those in the EU) accept the privacy policy during registration to be able to use Referee Hub. Those (EU) referees who already have an account need to accept it at the next login or visit.

**Comment by netzhuffle** [comment]
Should be done after #49.

**Comment by AfroDevGirl** [comment]
Look into using https://github.com/prey/gdpr_rails

**Comment by AfroDevGirl** [comment]
Finished with #157
