### ISSUE TITLE
Referees should be able to change their password

### ISSUE THREAD

**Issue by AfroDevGirl** [iqasport/referee_hub#59]
Refs need to be able to change the password in two scenarios:

1. If they forget their password
2. If they want to change it after they've logged in

Thankfully our authentication engine is configurable for this, so it should just be some configuration changes https://www.rubydoc.info/github/plataformatec/devise/. Will need to configure views on both the referee profile and add a link on the `/login` view.

**Comment by netzhuffle** [comment]
Forgotten password is in #60.

**Comment by AfroDevGirl** [comment]
Fixed via #60
