### ISSUE TITLE
Footer should be sticky on sign in pages

### ISSUE THREAD

**Issue by netzhuffle** [iqasport/referee_hub#62]
Minor styling issue on sign in, sign up and forgot password.

**Comment by jmc617** [comment]
Hi! Can I work on this?

**Comment by AfroDevGirl** [comment]
@jmc617 Hi Jessica, while this project is public we aren't prepared for contributors outside of our organization. Thanks so much for wanting to contribute but it wouldn't make sense for you to work on this issue. Check back in the future for issues that are open for outside contributors!

**Comment by AfroDevGirl** [comment]
fixed as part of #129
